import { MCPServer } from './agent';

export const BUILTIN_MCP_SERVERS: MCPServer[] = [
  {
    id: 'mcp-github',
    name: 'GitHub',
    description: 'Repository management, issues, PRs, file operations',
    icon: '🐙',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'github_list_repos', description: 'List your repositories', inputSchema: { per_page: { type: 'number' } } },
      { name: 'github_get_repo', description: 'Get repository details', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' } } },
      { name: 'github_get_file', description: 'Read file from repo', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' }, path: { type: 'string' } } },
      { name: 'github_list_issues', description: 'List issues', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' } } },
      { name: 'github_create_issue', description: 'Create an issue', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' }, title: { type: 'string' } } },
      { name: 'github_create_pr', description: 'Create pull request', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' }, title: { type: 'string' }, head: { type: 'string' }, base: { type: 'string' } } },
      { name: 'github_list_branches', description: 'List branches', inputSchema: { owner: { type: 'string' }, repo: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-vercel',
    name: 'Vercel',
    description: 'Deploy, manage projects, domains, and environment variables',
    icon: '▲',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'vercel_list_projects', description: 'List your Vercel projects', inputSchema: { limit: { type: 'number' } } },
      { name: 'vercel_get_project', description: 'Get project details', inputSchema: { projectId: { type: 'string' } } },
      { name: 'vercel_list_deployments', description: 'List deployments', inputSchema: { projectId: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'vercel_get_deployment', description: 'Get deployment details', inputSchema: { deploymentId: { type: 'string' } } },
      { name: 'vercel_create_deployment', description: 'Create a deployment', inputSchema: { name: { type: 'string' }, target: { type: 'string' } } },
      { name: 'vercel_list_domains', description: 'List project domains', inputSchema: { projectId: { type: 'string' } } },
      { name: 'vercel_add_domain', description: 'Add domain to project', inputSchema: { projectId: { type: 'string' }, domain: { type: 'string' } } },
      { name: 'vercel_list_env_vars', description: 'List environment variables', inputSchema: { projectId: { type: 'string' } } },
      { name: 'vercel_create_env_var', description: 'Create environment variable', inputSchema: { projectId: { type: 'string' }, key: { type: 'string' }, value: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-supabase',
    name: 'Supabase',
    description: 'Manage databases, storage buckets, auth users, and edge functions',
    icon: '⚡',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'supabase_list_projects', description: 'List all projects', inputSchema: {} },
      { name: 'supabase_get_project', description: 'Get project details', inputSchema: { ref: { type: 'string' } } },
      { name: 'supabase_list_tables', description: 'List public tables', inputSchema: { ref: { type: 'string' } } },
      { name: 'supabase_get_table_schema', description: 'Get column schema for a table', inputSchema: { ref: { type: 'string' }, table: { type: 'string' } } },
      { name: 'supabase_run_query', description: 'Run a read-only SQL query', inputSchema: { ref: { type: 'string' }, query: { type: 'string' } } },
      { name: 'supabase_list_buckets', description: 'List storage buckets', inputSchema: { ref: { type: 'string' } } },
      { name: 'supabase_list_users', description: 'List auth users', inputSchema: { ref: { type: 'string' } } },
      { name: 'supabase_list_functions', description: 'List edge functions', inputSchema: { ref: { type: 'string' } } },
      { name: 'supabase_get_function', description: 'Get edge function details', inputSchema: { ref: { type: 'string' }, slug: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-cloudflare',
    name: 'Cloudflare',
    description: 'Manage Workers, KV namespaces, DNS zones and records',
    icon: '☁️',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'cf_verify_token', description: 'Verify API token', inputSchema: {} },
      { name: 'cf_list_accounts', description: 'List accounts', inputSchema: {} },
      { name: 'cf_list_workers', description: 'List Workers scripts', inputSchema: { account_id: { type: 'string' } } },
      { name: 'cf_get_worker', description: 'Get Worker settings', inputSchema: { account_id: { type: 'string' }, script_name: { type: 'string' } } },
      { name: 'cf_delete_worker', description: 'Delete a Worker', inputSchema: { account_id: { type: 'string' }, script_name: { type: 'string' } } },
      { name: 'cf_list_kv_namespaces', description: 'List KV namespaces', inputSchema: { account_id: { type: 'string' } } },
      { name: 'cf_create_kv_namespace', description: 'Create KV namespace', inputSchema: { account_id: { type: 'string' }, title: { type: 'string' } } },
      { name: 'cf_list_kv_keys', description: 'List keys in a namespace', inputSchema: { account_id: { type: 'string' }, namespace_id: { type: 'string' } } },
      { name: 'cf_get_kv_value', description: 'Read a KV value', inputSchema: { account_id: { type: 'string' }, namespace_id: { type: 'string' }, key_name: { type: 'string' } } },
      { name: 'cf_put_kv_value', description: 'Write a KV value', inputSchema: { account_id: { type: 'string' }, namespace_id: { type: 'string' }, key_name: { type: 'string' }, value: { type: 'string' } } },
      { name: 'cf_list_zones', description: 'List DNS zones', inputSchema: {} },
      { name: 'cf_list_dns_records', description: 'List DNS records', inputSchema: { zone_id: { type: 'string' } } },
      { name: 'cf_create_dns_record', description: 'Create DNS record', inputSchema: { zone_id: { type: 'string' }, type: { type: 'string' }, name: { type: 'string' }, content: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-aws',
    name: 'AWS',
    description: 'Manage S3 buckets, Lambda functions, and Route 53 DNS',
    icon: '🔶',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'aws_verify_credentials', description: 'Verify AWS credentials via STS', inputSchema: {} },
      { name: 'aws_list_s3_buckets', description: 'List all S3 buckets', inputSchema: {} },
      { name: 'aws_list_s3_objects', description: 'List objects in a bucket', inputSchema: { bucket: { type: 'string' }, prefix: { type: 'string' }, max_keys: { type: 'number' } } },
      { name: 'aws_get_s3_object', description: 'Read an S3 object', inputSchema: { bucket: { type: 'string' }, key: { type: 'string' } } },
      { name: 'aws_delete_s3_object', description: 'Delete an S3 object', inputSchema: { bucket: { type: 'string' }, key: { type: 'string' } } },
      { name: 'aws_list_lambda_functions', description: 'List Lambda functions', inputSchema: {} },
      { name: 'aws_get_lambda_function', description: 'Get Lambda function details', inputSchema: { function_name: { type: 'string' } } },
      { name: 'aws_invoke_lambda', description: 'Invoke a Lambda function', inputSchema: { function_name: { type: 'string' }, payload: { type: 'object' } } },
      { name: 'aws_list_hosted_zones', description: 'List Route 53 hosted zones', inputSchema: {} },
      { name: 'aws_list_dns_records', description: 'List DNS records in a hosted zone', inputSchema: { hosted_zone_id: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-stripe',
    name: 'Stripe',
    description: 'Manage customers, products, subscriptions, invoices, and payments',
    icon: '💳',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'stripe_list_customers', description: 'List customers', inputSchema: { limit: { type: 'number' } } },
      { name: 'stripe_get_customer', description: 'Get customer details', inputSchema: { customer_id: { type: 'string' } } },
      { name: 'stripe_create_customer', description: 'Create a customer', inputSchema: { email: { type: 'string' }, name: { type: 'string' } } },
      { name: 'stripe_list_products', description: 'List products', inputSchema: { limit: { type: 'number' } } },
      { name: 'stripe_create_product', description: 'Create a product', inputSchema: { name: { type: 'string' }, description: { type: 'string' } } },
      { name: 'stripe_list_prices', description: 'List prices', inputSchema: { limit: { type: 'number' }, product: { type: 'string' } } },
      { name: 'stripe_create_price', description: 'Create a price', inputSchema: { unit_amount: { type: 'number' }, currency: { type: 'string' }, product: { type: 'string' } } },
      { name: 'stripe_list_subscriptions', description: 'List subscriptions', inputSchema: { limit: { type: 'number' }, customer: { type: 'string' } } },
      { name: 'stripe_get_subscription', description: 'Get subscription details', inputSchema: { subscription_id: { type: 'string' } } },
      { name: 'stripe_cancel_subscription', description: 'Cancel a subscription', inputSchema: { subscription_id: { type: 'string' } } },
      { name: 'stripe_list_payment_intents', description: 'List payment intents', inputSchema: { limit: { type: 'number' } } },
      { name: 'stripe_get_balance', description: 'Get account balance', inputSchema: {} },
      { name: 'stripe_list_invoices', description: 'List invoices', inputSchema: { limit: { type: 'number' }, customer: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-slack',
    name: 'Slack',
    description: 'Send messages, manage channels, users, and reactions',
    icon: '💬',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'slack_list_channels', description: 'List channels', inputSchema: { limit: { type: 'number' }, types: { type: 'string' } } },
      { name: 'slack_get_channel_info', description: 'Get channel details', inputSchema: { channel: { type: 'string' } } },
      { name: 'slack_post_message', description: 'Post a message to a channel', inputSchema: { channel: { type: 'string' }, text: { type: 'string' } } },
      { name: 'slack_update_message', description: 'Update a message', inputSchema: { channel: { type: 'string' }, ts: { type: 'string' }, text: { type: 'string' } } },
      { name: 'slack_delete_message', description: 'Delete a message', inputSchema: { channel: { type: 'string' }, ts: { type: 'string' } } },
      { name: 'slack_list_users', description: 'List workspace users', inputSchema: { limit: { type: 'number' } } },
      { name: 'slack_get_user_info', description: 'Get user details', inputSchema: { user: { type: 'string' } } },
      { name: 'slack_channel_history', description: 'Get channel message history', inputSchema: { channel: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'slack_set_topic', description: 'Set channel topic', inputSchema: { channel: { type: 'string' }, topic: { type: 'string' } } },
      { name: 'slack_add_reaction', description: 'Add a reaction to a message', inputSchema: { channel: { type: 'string' }, timestamp: { type: 'string' }, name: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-notion',
    name: 'Notion',
    description: 'Search pages, query databases, create and update content',
    icon: '📝',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'notion_search', description: 'Search pages and databases', inputSchema: { query: { type: 'string' }, page_size: { type: 'number' } } },
      { name: 'notion_get_page', description: 'Get page properties', inputSchema: { page_id: { type: 'string' } } },
      { name: 'notion_get_page_content', description: 'Get page block content', inputSchema: { block_id: { type: 'string' } } },
      { name: 'notion_create_page', description: 'Create a new page', inputSchema: { parent: { type: 'object' }, properties: { type: 'object' } } },
      { name: 'notion_update_page', description: 'Update page properties', inputSchema: { page_id: { type: 'string' }, properties: { type: 'object' } } },
      { name: 'notion_query_database', description: 'Query a database', inputSchema: { database_id: { type: 'string' }, filter: { type: 'object' } } },
      { name: 'notion_get_database', description: 'Get database schema', inputSchema: { database_id: { type: 'string' } } },
      { name: 'notion_list_databases', description: 'List all databases', inputSchema: { page_size: { type: 'number' } } },
      { name: 'notion_append_blocks', description: 'Append content blocks to a page', inputSchema: { block_id: { type: 'string' }, children: { type: 'array' } } },
      { name: 'notion_delete_block', description: 'Delete a block', inputSchema: { block_id: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-n8n',
    name: 'n8n',
    description: 'Manage workflows, executions, and trigger webhooks',
    icon: '🔄',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'n8n_list_workflows', description: 'List all workflows', inputSchema: { limit: { type: 'number' } } },
      { name: 'n8n_get_workflow', description: 'Get workflow details', inputSchema: { workflow_id: { type: 'string' } } },
      { name: 'n8n_activate_workflow', description: 'Activate a workflow', inputSchema: { workflow_id: { type: 'string' } } },
      { name: 'n8n_deactivate_workflow', description: 'Deactivate a workflow', inputSchema: { workflow_id: { type: 'string' } } },
      { name: 'n8n_list_executions', description: 'List workflow executions', inputSchema: { workflow_id: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'n8n_get_execution', description: 'Get execution details', inputSchema: { execution_id: { type: 'string' } } },
      { name: 'n8n_trigger_webhook', description: 'Trigger a webhook URL', inputSchema: { webhook_url: { type: 'string' }, payload: { type: 'object' } } },
      { name: 'n8n_list_credentials', description: 'List stored credentials', inputSchema: {} },
    ],
  },
  // ─── New MCP Servers ───
  {
    id: 'mcp-telegram',
    name: 'Telegram',
    description: 'Send messages, manage bots, channels, and webhooks',
    icon: '✈️',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'telegram_get_me', description: 'Get bot info', inputSchema: {} },
      { name: 'telegram_send_message', description: 'Send a message', inputSchema: { chat_id: { type: 'string' }, text: { type: 'string' }, parse_mode: { type: 'string' } } },
      { name: 'telegram_get_updates', description: 'Get recent updates', inputSchema: { limit: { type: 'number' }, offset: { type: 'number' } } },
      { name: 'telegram_get_chat', description: 'Get chat details', inputSchema: { chat_id: { type: 'string' } } },
      { name: 'telegram_get_chat_members_count', description: 'Get chat member count', inputSchema: { chat_id: { type: 'string' } } },
      { name: 'telegram_set_webhook', description: 'Set webhook URL', inputSchema: { url: { type: 'string' } } },
      { name: 'telegram_delete_webhook', description: 'Delete webhook', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-google-sheets',
    name: 'Google Sheets',
    description: 'Read, write, and manage Google Spreadsheets',
    icon: '📊',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'sheets_get_spreadsheet', description: 'Get spreadsheet metadata', inputSchema: { spreadsheet_id: { type: 'string' } } },
      { name: 'sheets_get_values', description: 'Read cell values', inputSchema: { spreadsheet_id: { type: 'string' }, range: { type: 'string' } } },
      { name: 'sheets_update_values', description: 'Update cell values', inputSchema: { spreadsheet_id: { type: 'string' }, range: { type: 'string' }, values: { type: 'array' } } },
      { name: 'sheets_append_values', description: 'Append rows', inputSchema: { spreadsheet_id: { type: 'string' }, range: { type: 'string' }, values: { type: 'array' } } },
      { name: 'sheets_clear_values', description: 'Clear cell range', inputSchema: { spreadsheet_id: { type: 'string' }, range: { type: 'string' } } },
      { name: 'sheets_create_spreadsheet', description: 'Create new spreadsheet', inputSchema: { title: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-coingecko',
    name: 'CoinGecko',
    description: 'Free crypto prices, market data, trending coins',
    icon: '🦎',
    enabled: false,
    requiresAuth: false,
    authConfigured: true,
    tools: [
      { name: 'coingecko_ping', description: 'Check API status', inputSchema: {} },
      { name: 'coingecko_price', description: 'Get price for coins', inputSchema: { ids: { type: 'string' }, vs_currencies: { type: 'string' } } },
      { name: 'coingecko_coin_detail', description: 'Get coin details', inputSchema: { id: { type: 'string' } } },
      { name: 'coingecko_market_chart', description: 'Get price chart data', inputSchema: { id: { type: 'string' }, vs_currency: { type: 'string' }, days: { type: 'number' } } },
      { name: 'coingecko_trending', description: 'Get trending coins', inputSchema: {} },
      { name: 'coingecko_markets', description: 'Get market listings', inputSchema: { vs_currency: { type: 'string' }, per_page: { type: 'number' }, page: { type: 'number' } } },
      { name: 'coingecko_search', description: 'Search coins', inputSchema: { query: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-alpha-vantage',
    name: 'Alpha Vantage',
    description: 'Stock quotes, forex, crypto, and technical indicators',
    icon: '📈',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'av_quote', description: 'Get stock quote', inputSchema: { symbol: { type: 'string' } } },
      { name: 'av_search', description: 'Search symbols', inputSchema: { keywords: { type: 'string' } } },
      { name: 'av_time_series_daily', description: 'Daily time series', inputSchema: { symbol: { type: 'string' }, outputsize: { type: 'string' } } },
      { name: 'av_time_series_intraday', description: 'Intraday time series', inputSchema: { symbol: { type: 'string' }, interval: { type: 'string' } } },
      { name: 'av_forex_rate', description: 'Get forex exchange rate', inputSchema: { from: { type: 'string' }, to: { type: 'string' } } },
      { name: 'av_crypto_rating', description: 'Get crypto rating', inputSchema: { symbol: { type: 'string' } } },
      { name: 'av_sma', description: 'Simple moving average', inputSchema: { symbol: { type: 'string' }, interval: { type: 'string' }, time_period: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-coinmarketcap',
    name: 'CoinMarketCap',
    description: 'Crypto rankings, market cap, exchange data',
    icon: '🪙',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'cmc_listings', description: 'Top crypto listings', inputSchema: { limit: { type: 'number' }, convert: { type: 'string' } } },
      { name: 'cmc_quotes', description: 'Get crypto quotes', inputSchema: { symbol: { type: 'string' }, id: { type: 'string' }, convert: { type: 'string' } } },
      { name: 'cmc_info', description: 'Get crypto metadata', inputSchema: { symbol: { type: 'string' }, id: { type: 'string' } } },
      { name: 'cmc_map', description: 'Map of all cryptos', inputSchema: { limit: { type: 'number' } } },
      { name: 'cmc_global_metrics', description: 'Global market metrics', inputSchema: { convert: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-defillama',
    name: 'DeFi Llama',
    description: 'DeFi TVL, protocol data, yields, stablecoins',
    icon: '🦙',
    enabled: false,
    requiresAuth: false,
    authConfigured: true,
    tools: [
      { name: 'defi_protocols', description: 'List all DeFi protocols', inputSchema: {} },
      { name: 'defi_protocol_tvl', description: 'Get protocol TVL history', inputSchema: { protocol: { type: 'string' } } },
      { name: 'defi_tvl_chains', description: 'TVL by chain', inputSchema: {} },
      { name: 'defi_global_tvl', description: 'Global TVL history', inputSchema: {} },
      { name: 'defi_yields', description: 'Top yield pools', inputSchema: { limit: { type: 'number' } } },
      { name: 'defi_stablecoins', description: 'Stablecoin market data', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-huggingface',
    name: 'Hugging Face',
    description: 'Run ML models, text generation, classification',
    icon: '🤗',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'hf_inference', description: 'Run model inference', inputSchema: { model: { type: 'string' }, inputs: { type: 'string' } } },
      { name: 'hf_list_models', description: 'Search models', inputSchema: { search: { type: 'string' }, limit: { type: 'number' }, sort: { type: 'string' } } },
      { name: 'hf_model_info', description: 'Get model details', inputSchema: { model_id: { type: 'string' } } },
      { name: 'hf_text_generation', description: 'Generate text', inputSchema: { prompt: { type: 'string' }, model: { type: 'string' }, max_tokens: { type: 'number' } } },
      { name: 'hf_text_classification', description: 'Classify text', inputSchema: { text: { type: 'string' }, model: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-docker',
    name: 'Docker',
    description: 'Manage containers, images, networks, volumes',
    icon: '🐳',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'docker_list_containers', description: 'List containers', inputSchema: { all: { type: 'boolean' } } },
      { name: 'docker_inspect_container', description: 'Inspect container', inputSchema: { container_id: { type: 'string' } } },
      { name: 'docker_start_container', description: 'Start container', inputSchema: { container_id: { type: 'string' } } },
      { name: 'docker_stop_container', description: 'Stop container', inputSchema: { container_id: { type: 'string' } } },
      { name: 'docker_list_images', description: 'List images', inputSchema: {} },
      { name: 'docker_list_networks', description: 'List networks', inputSchema: {} },
      { name: 'docker_list_volumes', description: 'List volumes', inputSchema: {} },
      { name: 'docker_system_info', description: 'Get system info', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-postgres',
    name: 'Postgres',
    description: 'Run read-only queries, inspect schemas and tables',
    icon: '🐘',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'pg_query', description: 'Run read-only SQL query', inputSchema: { query: { type: 'string' } } },
      { name: 'pg_list_tables', description: 'List all tables', inputSchema: {} },
      { name: 'pg_describe_table', description: 'Describe table columns', inputSchema: { table: { type: 'string' } } },
      { name: 'pg_list_schemas', description: 'List schemas', inputSchema: {} },
      { name: 'pg_table_sizes', description: 'Table sizes', inputSchema: { limit: { type: 'number' } } },
      { name: 'pg_active_connections', description: 'Active connections', inputSchema: { limit: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-digitalocean',
    name: 'DigitalOcean',
    description: 'Manage droplets, databases, domains, apps',
    icon: '🌊',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'do_account', description: 'Get account info', inputSchema: {} },
      { name: 'do_list_droplets', description: 'List droplets', inputSchema: { per_page: { type: 'number' } } },
      { name: 'do_get_droplet', description: 'Get droplet details', inputSchema: { droplet_id: { type: 'string' } } },
      { name: 'do_droplet_action', description: 'Perform droplet action', inputSchema: { droplet_id: { type: 'string' }, action_type: { type: 'string' } } },
      { name: 'do_list_databases', description: 'List databases', inputSchema: {} },
      { name: 'do_list_domains', description: 'List domains', inputSchema: {} },
      { name: 'do_list_apps', description: 'List apps', inputSchema: {} },
      { name: 'do_list_volumes', description: 'List volumes', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-twitter',
    name: 'X (Twitter)',
    description: 'Search tweets, lookup users, get trending data',
    icon: '𝕏',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'twitter_user_lookup', description: 'Lookup user by username', inputSchema: { username: { type: 'string' } } },
      { name: 'twitter_user_tweets', description: 'Get user tweets', inputSchema: { user_id: { type: 'string' }, max_results: { type: 'number' } } },
      { name: 'twitter_search_recent', description: 'Search recent tweets', inputSchema: { query: { type: 'string' }, max_results: { type: 'number' } } },
      { name: 'twitter_get_tweet', description: 'Get tweet by ID', inputSchema: { tweet_id: { type: 'string' } } },
      { name: 'twitter_user_followers', description: 'Get user followers', inputSchema: { user_id: { type: 'string' }, max_results: { type: 'number' } } },
      { name: 'twitter_trending', description: 'Search trending topics', inputSchema: { query: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-linkedin',
    name: 'LinkedIn',
    description: 'Post updates, manage profiles and company pages',
    icon: '💼',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'linkedin_me', description: 'Get your profile', inputSchema: {} },
      { name: 'linkedin_create_post', description: 'Create a post', inputSchema: { author: { type: 'string' }, text: { type: 'string' }, visibility: { type: 'string' } } },
      { name: 'linkedin_get_connections', description: 'Get connections', inputSchema: { start: { type: 'number' }, count: { type: 'number' } } },
      { name: 'linkedin_company_info', description: 'Get company info', inputSchema: { organization_id: { type: 'string' } } },
      { name: 'linkedin_company_posts', description: 'Get company posts', inputSchema: { organization_id: { type: 'string' }, count: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-twilio',
    name: 'Twilio SMS',
    description: 'Send SMS, manage phone numbers, calls, and lookups',
    icon: '📱',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'twilio_send_sms', description: 'Send an SMS message', inputSchema: { to: { type: 'string' }, from: { type: 'string' }, body: { type: 'string' } } },
      { name: 'twilio_list_messages', description: 'List SMS messages', inputSchema: { limit: { type: 'number' } } },
      { name: 'twilio_get_message', description: 'Get message details', inputSchema: { message_sid: { type: 'string' } } },
      { name: 'twilio_list_phone_numbers', description: 'List your phone numbers', inputSchema: {} },
      { name: 'twilio_get_phone_number', description: 'Get phone number details', inputSchema: { phone_sid: { type: 'string' } } },
      { name: 'twilio_list_calls', description: 'List call logs', inputSchema: { limit: { type: 'number' } } },
      { name: 'twilio_get_account', description: 'Get account info', inputSchema: {} },
      { name: 'twilio_lookup_phone', description: 'Lookup phone number info', inputSchema: { phone_number: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-zapier',
    name: 'Zapier',
    description: 'Trigger Zaps via webhooks and automate workflows',
    icon: '⚡',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'zapier_trigger_webhook', description: 'Trigger a Zap webhook', inputSchema: { payload: { type: 'object' } } },
      { name: 'zapier_trigger_with_data', description: 'Trigger with structured data + metadata', inputSchema: { data: { type: 'object' }, metadata: { type: 'object' } } },
      { name: 'zapier_validate_webhook', description: 'Validate a Zapier webhook URL', inputSchema: { webhook_url: { type: 'string' } } },
      { name: 'zapier_trigger_catch_hook', description: 'Trigger a Catch Hook', inputSchema: { payload: { type: 'object' } } },
      { name: 'zapier_multi_trigger', description: 'Trigger multiple webhooks at once', inputSchema: { webhook_urls: { type: 'array' }, payload: { type: 'object' } } },
    ],
  },
  {
    id: 'mcp-airtable',
    name: 'Airtable',
    description: 'Manage bases, tables, and records in Airtable',
    icon: '📋',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'airtable_list_bases', description: 'List all bases', inputSchema: {} },
      { name: 'airtable_get_base_schema', description: 'Get tables and fields for a base', inputSchema: { base_id: { type: 'string' } } },
      { name: 'airtable_list_records', description: 'List records in a table', inputSchema: { base_id: { type: 'string' }, table_id_or_name: { type: 'string' }, max_records: { type: 'number' }, view: { type: 'string' }, filter_formula: { type: 'string' } } },
      { name: 'airtable_get_record', description: 'Get a single record', inputSchema: { base_id: { type: 'string' }, table_id_or_name: { type: 'string' }, record_id: { type: 'string' } } },
      { name: 'airtable_create_records', description: 'Create new records', inputSchema: { base_id: { type: 'string' }, table_id_or_name: { type: 'string' }, records: { type: 'array' } } },
      { name: 'airtable_update_records', description: 'Update existing records', inputSchema: { base_id: { type: 'string' }, table_id_or_name: { type: 'string' }, records: { type: 'array' } } },
      { name: 'airtable_delete_records', description: 'Delete records', inputSchema: { base_id: { type: 'string' }, table_id_or_name: { type: 'string' }, record_ids: { type: 'array' } } },
      { name: 'airtable_create_table', description: 'Create a new table', inputSchema: { base_id: { type: 'string' }, name: { type: 'string' }, fields: { type: 'array' } } },
    ],
  },
  {
    id: 'mcp-jira',
    name: 'Jira',
    description: 'Manage issues, sprints, projects, and workflows',
    icon: '🎯',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'jira_list_projects', description: 'List all projects', inputSchema: {} },
      { name: 'jira_get_project', description: 'Get project details', inputSchema: { project_key: { type: 'string' } } },
      { name: 'jira_search_issues', description: 'Search issues with JQL', inputSchema: { jql: { type: 'string' }, max_results: { type: 'number' } } },
      { name: 'jira_get_issue', description: 'Get issue details', inputSchema: { issue_key: { type: 'string' } } },
      { name: 'jira_create_issue', description: 'Create an issue', inputSchema: { project_key: { type: 'string' }, summary: { type: 'string' }, issue_type: { type: 'string' }, description: { type: 'string' } } },
      { name: 'jira_update_issue', description: 'Update issue fields', inputSchema: { issue_key: { type: 'string' }, fields: { type: 'object' } } },
      { name: 'jira_transition_issue', description: 'Transition issue status', inputSchema: { issue_key: { type: 'string' }, transition_id: { type: 'string' } } },
      { name: 'jira_get_transitions', description: 'Get available transitions', inputSchema: { issue_key: { type: 'string' } } },
      { name: 'jira_add_comment', description: 'Add a comment', inputSchema: { issue_key: { type: 'string' }, body: { type: 'string' } } },
      { name: 'jira_list_sprints', description: 'List sprints for a board', inputSchema: { board_id: { type: 'string' }, state: { type: 'string' } } },
      { name: 'jira_get_sprint_issues', description: 'Get issues in a sprint', inputSchema: { sprint_id: { type: 'string' }, max_results: { type: 'number' } } },
      { name: 'jira_assign_issue', description: 'Assign issue to user', inputSchema: { issue_key: { type: 'string' }, account_id: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-salesforce',
    name: 'Salesforce',
    description: 'Manage leads, contacts, opportunities, and CRM data',
    icon: '☁️',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'sf_query', description: 'Run a SOQL query', inputSchema: { soql: { type: 'string' } } },
      { name: 'sf_get_record', description: 'Get a record by ID', inputSchema: { object_type: { type: 'string' }, record_id: { type: 'string' } } },
      { name: 'sf_create_record', description: 'Create a record', inputSchema: { object_type: { type: 'string' }, fields: { type: 'object' } } },
      { name: 'sf_update_record', description: 'Update a record', inputSchema: { object_type: { type: 'string' }, record_id: { type: 'string' }, fields: { type: 'object' } } },
      { name: 'sf_delete_record', description: 'Delete a record', inputSchema: { object_type: { type: 'string' }, record_id: { type: 'string' } } },
      { name: 'sf_describe_object', description: 'Describe object schema', inputSchema: { object_type: { type: 'string' } } },
      { name: 'sf_list_objects', description: 'List all objects', inputSchema: {} },
      { name: 'sf_search', description: 'SOSL search', inputSchema: { sosl: { type: 'string' } } },
      { name: 'sf_list_leads', description: 'List recent leads', inputSchema: { limit: { type: 'number' } } },
      { name: 'sf_list_contacts', description: 'List recent contacts', inputSchema: { limit: { type: 'number' } } },
      { name: 'sf_list_opportunities', description: 'List recent opportunities', inputSchema: { limit: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-hubspot',
    name: 'HubSpot',
    description: 'Manage contacts, deals, companies, and pipelines',
    icon: '🟠',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'hubspot_list_contacts', description: 'List contacts', inputSchema: { limit: { type: 'number' } } },
      { name: 'hubspot_get_contact', description: 'Get contact details', inputSchema: { contact_id: { type: 'string' } } },
      { name: 'hubspot_create_contact', description: 'Create a contact', inputSchema: { properties: { type: 'object' } } },
      { name: 'hubspot_update_contact', description: 'Update a contact', inputSchema: { contact_id: { type: 'string' }, properties: { type: 'object' } } },
      { name: 'hubspot_list_deals', description: 'List deals', inputSchema: { limit: { type: 'number' } } },
      { name: 'hubspot_get_deal', description: 'Get deal details', inputSchema: { deal_id: { type: 'string' } } },
      { name: 'hubspot_create_deal', description: 'Create a deal', inputSchema: { properties: { type: 'object' } } },
      { name: 'hubspot_update_deal', description: 'Update a deal', inputSchema: { deal_id: { type: 'string' }, properties: { type: 'object' } } },
      { name: 'hubspot_list_companies', description: 'List companies', inputSchema: { limit: { type: 'number' } } },
      { name: 'hubspot_create_company', description: 'Create a company', inputSchema: { properties: { type: 'object' } } },
      { name: 'hubspot_list_pipelines', description: 'List pipelines', inputSchema: { object_type: { type: 'string' } } },
      { name: 'hubspot_search', description: 'Search CRM objects', inputSchema: { object_type: { type: 'string' }, query: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'hubspot_list_owners', description: 'List owners', inputSchema: { limit: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-monday',
    name: 'Monday.com',
    description: 'Manage boards, items, groups, and updates',
    icon: '📅',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'monday_list_boards', description: 'List boards', inputSchema: { limit: { type: 'number' } } },
      { name: 'monday_get_board', description: 'Get board details', inputSchema: { board_id: { type: 'string' } } },
      { name: 'monday_list_items', description: 'List items in a board', inputSchema: { board_id: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'monday_get_item', description: 'Get item details', inputSchema: { item_id: { type: 'string' } } },
      { name: 'monday_create_item', description: 'Create an item', inputSchema: { board_id: { type: 'string' }, item_name: { type: 'string' }, group_id: { type: 'string' }, column_values: { type: 'object' } } },
      { name: 'monday_update_item', description: 'Update item columns', inputSchema: { board_id: { type: 'string' }, item_id: { type: 'string' }, column_values: { type: 'object' } } },
      { name: 'monday_delete_item', description: 'Delete an item', inputSchema: { item_id: { type: 'string' } } },
      { name: 'monday_add_update', description: 'Add an update to an item', inputSchema: { item_id: { type: 'string' }, body: { type: 'string' } } },
      { name: 'monday_list_groups', description: 'List groups in a board', inputSchema: { board_id: { type: 'string' } } },
      { name: 'monday_create_group', description: 'Create a group', inputSchema: { board_id: { type: 'string' }, group_name: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-asana',
    name: 'Asana',
    description: 'Manage tasks, projects, workspaces, and sections',
    icon: '🎯',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'asana_list_workspaces', description: 'List workspaces', inputSchema: {} },
      { name: 'asana_list_projects', description: 'List projects', inputSchema: { workspace_gid: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'asana_get_project', description: 'Get project details', inputSchema: { project_gid: { type: 'string' } } },
      { name: 'asana_list_tasks', description: 'List tasks', inputSchema: { project_gid: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'asana_get_task', description: 'Get task details', inputSchema: { task_gid: { type: 'string' } } },
      { name: 'asana_create_task', description: 'Create a task', inputSchema: { name: { type: 'string' }, projects: { type: 'array' }, assignee: { type: 'string' }, due_on: { type: 'string' }, notes: { type: 'string' } } },
      { name: 'asana_update_task', description: 'Update a task', inputSchema: { task_gid: { type: 'string' }, fields: { type: 'object' } } },
      { name: 'asana_delete_task', description: 'Delete a task', inputSchema: { task_gid: { type: 'string' } } },
      { name: 'asana_add_comment', description: 'Add a comment', inputSchema: { task_gid: { type: 'string' }, text: { type: 'string' } } },
      { name: 'asana_list_sections', description: 'List project sections', inputSchema: { project_gid: { type: 'string' } } },
      { name: 'asana_search_tasks', description: 'Search tasks', inputSchema: { workspace_gid: { type: 'string' }, text: { type: 'string' }, completed: { type: 'boolean' } } },
    ],
  },
  {
    id: 'mcp-discord',
    name: 'Discord',
    description: 'Manage servers, channels, messages, and members',
    icon: '🎮',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'discord_get_me', description: 'Get bot info', inputSchema: {} },
      { name: 'discord_list_guilds', description: 'List servers', inputSchema: {} },
      { name: 'discord_get_guild', description: 'Get server details', inputSchema: { guild_id: { type: 'string' } } },
      { name: 'discord_list_channels', description: 'List channels', inputSchema: { guild_id: { type: 'string' } } },
      { name: 'discord_get_channel', description: 'Get channel details', inputSchema: { channel_id: { type: 'string' } } },
      { name: 'discord_create_channel', description: 'Create a channel', inputSchema: { guild_id: { type: 'string' }, name: { type: 'string' }, type: { type: 'number' }, topic: { type: 'string' } } },
      { name: 'discord_delete_channel', description: 'Delete a channel', inputSchema: { channel_id: { type: 'string' } } },
      { name: 'discord_send_message', description: 'Send a message', inputSchema: { channel_id: { type: 'string' }, content: { type: 'string' }, embeds: { type: 'array' } } },
      { name: 'discord_get_messages', description: 'Get channel messages', inputSchema: { channel_id: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'discord_edit_message', description: 'Edit a message', inputSchema: { channel_id: { type: 'string' }, message_id: { type: 'string' }, content: { type: 'string' } } },
      { name: 'discord_delete_message', description: 'Delete a message', inputSchema: { channel_id: { type: 'string' }, message_id: { type: 'string' } } },
      { name: 'discord_add_reaction', description: 'Add a reaction', inputSchema: { channel_id: { type: 'string' }, message_id: { type: 'string' }, emoji: { type: 'string' } } },
      { name: 'discord_list_members', description: 'List server members', inputSchema: { guild_id: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'discord_get_member', description: 'Get member details', inputSchema: { guild_id: { type: 'string' }, user_id: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-trello',
    name: 'Trello',
    description: 'Manage boards, lists, cards, and members',
    icon: '📌',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'trello_list_boards', description: 'List your boards', inputSchema: {} },
      { name: 'trello_get_board', description: 'Get board details', inputSchema: { board_id: { type: 'string' } } },
      { name: 'trello_list_lists', description: 'List lists in a board', inputSchema: { board_id: { type: 'string' } } },
      { name: 'trello_create_list', description: 'Create a list', inputSchema: { board_id: { type: 'string' }, name: { type: 'string' } } },
      { name: 'trello_list_cards', description: 'List cards in a list', inputSchema: { list_id: { type: 'string' } } },
      { name: 'trello_get_card', description: 'Get card details', inputSchema: { card_id: { type: 'string' } } },
      { name: 'trello_create_card', description: 'Create a card', inputSchema: { list_id: { type: 'string' }, name: { type: 'string' }, desc: { type: 'string' } } },
      { name: 'trello_update_card', description: 'Update a card', inputSchema: { card_id: { type: 'string' }, fields: { type: 'object' } } },
      { name: 'trello_delete_card', description: 'Delete a card', inputSchema: { card_id: { type: 'string' } } },
      { name: 'trello_move_card', description: 'Move card to another list', inputSchema: { card_id: { type: 'string' }, list_id: { type: 'string' } } },
      { name: 'trello_add_comment', description: 'Add a comment to a card', inputSchema: { card_id: { type: 'string' }, text: { type: 'string' } } },
      { name: 'trello_list_members', description: 'List board members', inputSchema: { board_id: { type: 'string' } } },
      { name: 'trello_list_labels', description: 'List board labels', inputSchema: { board_id: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-sendgrid',
    name: 'SendGrid',
    description: 'Send emails, manage contacts, lists, templates, and stats',
    icon: '📧',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'sendgrid_send_email', description: 'Send an email', inputSchema: { to: { type: 'string' }, from: { type: 'string' }, subject: { type: 'string' }, text: { type: 'string' }, html: { type: 'string' } } },
      { name: 'sendgrid_list_contacts', description: 'List contacts', inputSchema: { page_size: { type: 'number' } } },
      { name: 'sendgrid_search_contacts', description: 'Search contacts', inputSchema: { query: { type: 'string' } } },
      { name: 'sendgrid_add_contacts', description: 'Add/update contacts', inputSchema: { contacts: { type: 'array' }, list_ids: { type: 'array' } } },
      { name: 'sendgrid_delete_contacts', description: 'Delete contacts', inputSchema: { ids: { type: 'array' } } },
      { name: 'sendgrid_list_lists', description: 'List contact lists', inputSchema: { page_size: { type: 'number' } } },
      { name: 'sendgrid_create_list', description: 'Create a list', inputSchema: { name: { type: 'string' } } },
      { name: 'sendgrid_delete_list', description: 'Delete a list', inputSchema: { list_id: { type: 'string' } } },
      { name: 'sendgrid_list_templates', description: 'List email templates', inputSchema: { generations: { type: 'string' }, page_size: { type: 'number' } } },
      { name: 'sendgrid_get_template', description: 'Get template details', inputSchema: { template_id: { type: 'string' } } },
      { name: 'sendgrid_get_stats', description: 'Get email stats', inputSchema: { start_date: { type: 'string' }, end_date: { type: 'string' } } },
      { name: 'sendgrid_list_senders', description: 'List verified senders', inputSchema: {} },
    ],
  },
  // ─── Web3 MCP Servers ───
  {
    id: 'mcp-evm-rpc',
    name: 'EVM RPC',
    description: 'Read EVM chain state: balances, blocks, logs, transactions, gas',
    icon: '⛓️',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'evm_block_number', description: 'Get latest block number', inputSchema: {} },
      { name: 'evm_get_balance', description: 'Get ETH balance of address', inputSchema: { address: { type: 'string' }, block: { type: 'string' } } },
      { name: 'evm_call', description: 'Execute eth_call (read-only)', inputSchema: { to: { type: 'string' }, data: { type: 'string' }, from: { type: 'string' }, block: { type: 'string' } } },
      { name: 'evm_get_logs', description: 'Query event logs', inputSchema: { address: { type: 'string' }, topics: { type: 'array' }, fromBlock: { type: 'string' }, toBlock: { type: 'string' } } },
      { name: 'evm_get_code', description: 'Get contract bytecode', inputSchema: { address: { type: 'string' }, block: { type: 'string' } } },
      { name: 'evm_estimate_gas', description: 'Estimate gas for transaction', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' } } },
      { name: 'evm_get_transaction', description: 'Get transaction by hash', inputSchema: { hash: { type: 'string' } } },
      { name: 'evm_get_transaction_receipt', description: 'Get transaction receipt', inputSchema: { hash: { type: 'string' } } },
      { name: 'evm_get_block', description: 'Get block by number', inputSchema: { block: { type: 'string' }, full_transactions: { type: 'boolean' } } },
      { name: 'evm_chain_id', description: 'Get chain ID', inputSchema: {} },
      { name: 'evm_gas_price', description: 'Get current gas price', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-contract-intel',
    name: 'Contract Intelligence',
    description: 'Inspect verified contracts: ABI, source, events, decode calldata',
    icon: '📜',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'contract_get_abi', description: 'Get contract ABI from explorer', inputSchema: { address: { type: 'string' } } },
      { name: 'contract_get_source', description: 'Get verified source code', inputSchema: { address: { type: 'string' } } },
      { name: 'contract_verified_status', description: 'Check verification status', inputSchema: { address: { type: 'string' } } },
      { name: 'contract_decode_calldata', description: 'Decode transaction calldata', inputSchema: { data: { type: 'string' }, abi: { type: 'array' } } },
      { name: 'contract_get_creation_tx', description: 'Get contract creation transaction', inputSchema: { address: { type: 'string' } } },
      { name: 'contract_get_events', description: 'Get contract events/logs', inputSchema: { address: { type: 'string' }, fromBlock: { type: 'string' }, toBlock: { type: 'string' }, topic0: { type: 'string' } } },
      { name: 'contract_get_transactions', description: 'Get contract transactions', inputSchema: { address: { type: 'string' }, page: { type: 'number' }, offset: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-solana',
    name: 'Solana',
    description: 'Solana chain data: accounts, tokens, transactions, programs',
    icon: '🟣',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'solana_get_balance', description: 'Get SOL balance', inputSchema: { address: { type: 'string' } } },
      { name: 'solana_get_account_info', description: 'Get account details', inputSchema: { address: { type: 'string' }, encoding: { type: 'string' } } },
      { name: 'solana_get_transaction', description: 'Get parsed transaction', inputSchema: { signature: { type: 'string' } } },
      { name: 'solana_get_signatures', description: 'Get recent signatures for address', inputSchema: { address: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'solana_get_token_accounts', description: 'Get token accounts for wallet', inputSchema: { address: { type: 'string' }, program_id: { type: 'string' } } },
      { name: 'solana_get_program_accounts', description: 'Get program accounts', inputSchema: { program_id: { type: 'string' }, limit: { type: 'number' }, filters: { type: 'array' } } },
      { name: 'solana_get_slot', description: 'Get current slot', inputSchema: {} },
      { name: 'solana_get_block_height', description: 'Get current block height', inputSchema: {} },
      { name: 'solana_get_recent_blockhash', description: 'Get latest blockhash', inputSchema: {} },
      { name: 'solana_get_supply', description: 'Get SOL supply info', inputSchema: {} },
      { name: 'solana_get_epoch_info', description: 'Get current epoch info', inputSchema: {} },
      { name: 'solana_get_nft_metadata', description: 'Get NFT token metadata', inputSchema: { mint: { type: 'string' } } },
    ],
  },
  {
    id: 'mcp-tx-simulator',
    name: 'Transaction Simulator',
    description: 'Simulate, trace, sign and send EVM transactions with wallet support',
    icon: '🧪',
    enabled: false,
    requiresAuth: true,
    authConfigured: false,
    tools: [
      { name: 'sim_eth_call', description: 'Dry-run transaction via eth_call', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' }, block: { type: 'string' } } },
      { name: 'sim_estimate_gas', description: 'Estimate gas with cost breakdown', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' } } },
      { name: 'sim_trace_call', description: 'Trace call execution (requires archive node)', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' }, block: { type: 'string' } } },
      { name: 'sim_tenderly_simulate', description: 'Full simulation via Tenderly API', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' }, chain_id: { type: 'number' }, save: { type: 'boolean' } } },
      { name: 'sim_compare_gas', description: 'Compare gas costs of multiple calls', inputSchema: { calls: { type: 'array' } } },
      { name: 'sim_decode_revert', description: 'Simulate and decode revert reason', inputSchema: { from: { type: 'string' }, to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' } } },
      { name: 'wallet_send_transaction', description: 'Sign & send transaction via connected wallet (requires approval)', inputSchema: { to: { type: 'string' }, data: { type: 'string' }, value: { type: 'string' }, gas: { type: 'string' } } },
      { name: 'wallet_sign_message', description: 'Sign a message with connected wallet', inputSchema: { message: { type: 'string' } } },
      { name: 'wallet_get_address', description: 'Get connected wallet address and chain', inputSchema: {} },
    ],
  },
  {
    id: 'mcp-firecrawl',
    name: 'Firecrawl',
    description: 'AI-powered web scraping, search, and crawling',
    icon: '🔥',
    enabled: false,
    requiresAuth: false,
    authConfigured: true,
    tools: [
      { name: 'firecrawl_scrape', description: 'Scrape a URL', inputSchema: { url: { type: 'string' }, formats: { type: 'array' } } },
      { name: 'firecrawl_search', description: 'Search the web', inputSchema: { query: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'firecrawl_map', description: 'Map website URLs', inputSchema: { url: { type: 'string' }, limit: { type: 'number' } } },
      { name: 'firecrawl_crawl', description: 'Crawl entire website', inputSchema: { url: { type: 'string' }, limit: { type: 'number' } } },
    ],
  },
  {
    id: 'mcp-perplexity',
    name: 'Perplexity',
    description: 'AI-powered search with grounded answers and citations',
    icon: '🔍',
    enabled: false,
    requiresAuth: false,
    authConfigured: true,
    tools: [
      { name: 'perplexity_search', description: 'Search with AI', inputSchema: { query: { type: 'string' }, model: { type: 'string' }, recency: { type: 'string' } } },
      { name: 'perplexity_research', description: 'Deep research', inputSchema: { query: { type: 'string' } } },
      { name: 'perplexity_reason', description: 'Chain-of-thought reasoning', inputSchema: { query: { type: 'string' } } },
    ],
  },
];
