// This file is automatically generated. Do not edit it directly.
// MIGRATED: Now using db-client.ts with Privy auth and Vercel Functions

// Re-export the new database client
export { supabase, setDbAccessTokenGetter } from '@/lib/db-client';
